### ISSUE TITLE
Issue with the tutorial

### ISSUE THREAD

**Issue by SalimMegat** [imsb-uke/DISSECT#4]
Hi, 

I'd be interested in using the tool for some deconvolution benchmarks on my dataset. 
However, the tutorial does not seem to run through. It throws an error : 
It seems to be an issue with the np.concatenate not being able to concatenate X_celltypes which is a sparse matrix to the np array "data"...

Thanks for your help ! 

numpy version : 1.26.3

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[25], line 2
      1 # Estimate cell type specific gene expression
----> 2 dissect.run_dissect_expr(config)
      3 numpy.__version__

File ~/.conda/envs/dissect/lib/python3.9/site-packages/dissect/dissect_expr.py:112, in run_dissect_expr(config)
    109 X_real = X_real / max_val
    111 for celltype in X_celltypes.keys():
--> 112     X_celltypes[celltype] = np.concatenate(
    113         [
    114             X_celltypes[celltype],
    115             np.array(data.obs[celltype]).reshape((data.shape[0], 1)),
    116         ],
    117         1,
    118     )
    120 X_sim_input = np.repeat(X_sim, repeats=df.shape[0], axis=0)
    121 labels = np.concatenate([hot_encoding] * X_sim.shape[0], axis=0)

ValueError: zero-dimensional arrays cannot be concatenated

**Comment by SalimMegat** [comment]
Forgot to mention: the error happens on the second part of the script : dissect.run_dissect_expr(config)

Best, 

Salim.

**Comment by robinredX** [comment]
Hi Salim, pardon me for the late response, I somehow missed the issue notification. It shouldn't happen as the tutorial ran succesfully when I pushed, but may be something off with the data. I'll check and update soon!

**Comment by robinredX** [comment]
Occurs with differing versions of scanpy, anndata and h5py, when arrays are saved as sparse matrices in data.layers. Fixed in commit [9e90e63](https://github.com/imsb-uke/DISSECT/commit/9e90e63fa579c690bae65a869845a4b386e63ad7).
