### ISSUE TITLE
import issue of keras.layers concatenate

### ISSUE THREAD

**Issue by rhjvedder** [imsb-uke/DISSECT#5]
within dissect/dissect_expr.py line 26,
`from keras.layer.merge import concatenate as concat`
causes a module does not exist error
should be
`from keras.layers import concatenate as concat`

**Comment by robinredX** [comment]
Thanks! I'm unable to reproduce. With Keras 2.7.0, it works for me. Could you check your keras version?
![image](https://github.com/user-attachments/assets/07296fe1-52a4-45c1-81c3-7fb4a41c499e)

**Comment by robinredX** [comment]
actually, importing concatenate from both keras.layers.merge and keras.layers should work. Also, line 26 is `from keras.layers.merge import concatenate as concat` not from `keras.layer.merge import concatenate as concat`. Could you check if source files were modified somehow?
![image](https://github.com/user-attachments/assets/8f5b5f4a-0fdd-4e80-88df-47cb2c65d3b4)
